In [2]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


In [3]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


In [4]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


In [6]:
# this is your code to get two vectors

x1 = X[:, 0]
x2 = X[:, -2]

print(x1)
print(x2)

[18.0 15.0 18.0 16.0 17.0 15.0 14.0 14.0 14.0 15.0 0.0 0.0 0.0 0.0 0.0
 15.0 14.0 0.0 15.0 14.0 24.0 22.0 18.0 21.0 27.0 26.0 25.0 24.0 25.0 26.0
 21.0 10.0 10.0 11.0 9.0 27.0 28.0 25.0 25.0 0.0 19.0 16.0 17.0 19.0 18.0
 14.0 14.0 14.0 14.0 12.0 13.0 13.0 18.0 22.0 19.0 18.0 23.0 28.0 30.0
 30.0 31.0 35.0 27.0 26.0 24.0 25.0 23.0 20.0 21.0 13.0 14.0 15.0 14.0
 17.0 11.0 13.0 12.0 13.0 19.0 15.0 13.0 13.0 14.0 18.0 22.0 21.0 26.0
 22.0 28.0 23.0 28.0 27.0 13.0 14.0 13.0 14.0 15.0 12.0 13.0 13.0 14.0
 13.0 12.0 13.0 18.0 16.0 18.0 18.0 23.0 26.0 11.0 12.0 13.0 12.0 18.0
 20.0 21.0 22.0 18.0 19.0 21.0 26.0 15.0 16.0 29.0 24.0 20.0 19.0 15.0
 24.0 20.0 11.0 20.0 21.0 19.0 15.0 31.0 26.0 32.0 25.0 16.0 16.0 18.0
 16.0 13.0 14.0 14.0 14.0 29.0 26.0 26.0 31.0 32.0 28.0 24.0 26.0 24.0
 26.0 31.0 19.0 18.0 15.0 15.0 16.0 15.0 16.0 14.0 17.0 16.0 15.0 18.0
 21.0 20.0 13.0 29.0 23.0 20.0 23.0 24.0 25.0 24.0 18.0 29.0 19.0 23.0
 23.0 22.0 25.0 33.0 28.0 25.0 25.0 26.0 27.0 17.5 16.0 15.5 14.5 22.0

In [9]:
#1. addition and subtraction

x1 = X[:, 0]
x2 = X[:, -2]

y = x1 + x2
z = x1 - x2

#2. element-wise multiplication

y2 = np.multiply(x1, x2)
print(y2)

#3. Inner product

y3 = np.inner(x1, x2)
print(y3)

# 4. three norms

y4 = np.linalg.norm(x1, ord=1)
print(y4)
y5 = np.linalg.norm(x1, ord=2)
print(y5)
y6 = np.linalg.norm(x1, ord=np.inf)
print(y6)

# 5. compute the distance between these two vectors

y7 = np.linalg.norm(x2-x1, ord=2)
print(y7)

[216.0 172.5 198.0 192.0 178.5 150.0 126.0 119.0 140.0 127.5 0.0 0.0 0.0
 0.0 0.0 150.0 112.0 0.0 142.5 140.0 360.0 341.0 279.0 336.0 391.5 533.0
 437.5 348.0 437.5 325.0 315.0 140.0 150.0 148.5 166.5 391.5 434.0 350.0
 475.0 0.0 247.0 248.0 263.5 294.5 279.0 168.0 161.0 189.0 182.0 138.0
 156.0 156.0 243.0 418.0 285.0 261.0 322.0 392.0 585.0 435.0 589.0 630.0
 513.0 533.0 372.0 425.0 540.5 390.0 346.5 156.0 168.0 202.5 182.0 195.5
 121.0 175.5 162.0 162.5 256.5 187.5 182.0 208.0 196.0 261.0 396.0 409.5
 468.0 352.0 476.0 333.5 420.0 445.5 169.0 161.0 169.0 203.0 187.5 138.0
 156.0 169.0 203.0 143.0 132.0 143.0 297.0 288.0 288.0 297.0 368.0 546.0
 154.0 150.0 169.0 150.0 270.0 380.0 409.5 363.0 243.0 351.5 294.0 403.0
 195.0 152.0 565.5 372.0 280.0 294.5 165.0 336.0 270.0 121.0 330.0 357.0
 304.0 255.0 589.0 429.0 672.0 425.0 272.0 288.0 297.0 224.0 188.5 189.0
 224.0 217.0 478.5 403.0 377.0 511.5 608.0 406.0 372.0 364.0 360.0 403.0
 496.0 304.0 288.0 315.0 292.5 184.0 210.0 232.0 189.

In [14]:
# this is your code to get two matrices: A, B

A = X[0:2, :]
B = X[3:5, :]

print(A)
print(B)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]]
[[16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]


In [23]:
# 1. addition and subtraction 

print(A + B)
print(A - B)

# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C

C = np.transpose(B)
print(str(len(C)) + ', ' + str(len(C[0])))

# 3. compute the product between A and C, and print the result and its shape

dot = np.dot(A, C)
print(dot)
print(str(len(dot)) + ', ' + str(len(dot[0])))

# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D

D = np.transpose(A)
print(str(len(D)) + ', ' + str(len(D[0])))

# 5. compute the product between D and B, and print the result and its shape

dot1 = np.dot(D, B)
print(dot1)
print(str(len(dot1)) + ', ' + str(len(dot1[0])))


[[34.0 16 611.0 280 6937 24.0 140]
 [32.0 16 652.0 305 7142 22.0 140]]
[[2.0 0 3.0 -20 71 0.0 0]
 [-2.0 0 48.0 25 244 1.0 0]]
7, 2
[[12147456.0 12201606.0]
 [12814561.0 12871296.75]]
2, 2
7, 2
[[543.0 264.0 10002.0 4800.0 113529.0 373.5 2310.0]
 [264.0 128 4848.0 2320 55056 180.0 1120]
 [10862.0 5256.0 199028.0 95050.0 2261081.0 7359.0 45990.0]
 [4885.0 2360 89350.0 42600 1015375 3292.5 20650]
 [118845.0 57576 2180502.0 1042620 24766389 80824.5 503790]
 [387.5 188.0 7121.0 3410.0 80859.5 264.75 1645.0]
 [2310.0 1120 42420.0 20300 481740 1575.0 9800]]
7, 7
